"""init

Revision ID: 354bb6582d83
Revises: 
Create Date: 2025-09-30 15:09:14.791032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354bb6582d83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_table('matchtime',
    sa.Column('matchtime_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('matchtime_id')
    )
    op.create_table('stadium',
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stadium_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('photo_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('stadium_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('matchtime_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('pay', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.manager_id'], ),
    sa.ForeignKeyConstraint(['matchtime_id'], ['matchtime.matchtime_id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.stadium_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermatch',
    sa.Column('usermatch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stadium_match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stadium_match_id'], ['stadium_match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usermatch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermatch')
    op.drop_table('stadium_match')
    op.drop_table('user')
    op.drop_table('stadium')
    op.drop_table('matchtime')
    op.drop_table('manager')
    # ### end Alembic commands ###
