"""empty message

Revision ID: 63fb912d4478
Revises: 354bb6582d83
Create Date: 2025-10-23 13:08:10.743448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fb912d4478'
down_revision = '354bb6582d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p_number', sa.String(length=15), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('p_number')
        batch_op.drop_column('pay')

    # ### end Alembic commands ###
